### ISSUE TITLE
Next instance of word

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#10]
`#` = jumps to next occurrence of the word the cursor was one when you hit `#` or toggles between if only two of them. etc.

**Comment by Alexey-T** [comment]
3 is number. # ? Description- I cannot understand

**Comment by mangobait** [comment]
It should be:

#

and it jumps the cursor to the next instance of the word it is one---like
find as if you were doing a find for the word the cursor is on (without
going through a find protocol).

2017-10-03 9:05 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
It is done. Pls test.

**Comment by mangobait** [comment]
Yes, works. Best if the word can be highlighted somehow to draw the eye to
it; otherwise it has less utility.

2017-10-05 3:03 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
how Vim hilites word in this case? I dont see.

**Comment by Alexey-T** [comment]
Plugin "Hilite All Occurences" will do this, pls install it
It has Config command- enter this config
```
[op]
min_len=2
sel_allow=1
sel_allow_white_space=0
sel_case_sensitive=0
sel_words_only=1
sel_whole_words=1
caret_allow=1
caret_case_sensitive=1
caret_whole_words=1
```

**Comment by mangobait** [comment]
ST in vim does. Maybe it's an ST thing. Sorry.

2017-10-05 15:00 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
See above comment about Hilite plugin.
Pls test.
