### ISSUE TITLE
gg/G

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#11]
gg= cursor to top of file
G = cursor to bottom of file

**Comment by Alexey-T** [comment]
done 'gg', 'G', number+'G'
You can download and test.

**Comment by mangobait** [comment]
Fuller version of G:

G | goto line number prefixed, or goto end if none

Others related to movement, from 
https://hea-www.harvard.edu/~fine/Tech/vi.html :

H | home cursor - goto first line on screen

L | goto last line on screen

M | goto middle line on screen

( | move to previous sentence

) | move to next sentence

+ | move to first non-whitespace of next line

[ | move to previous "{...}" section | "["

] | move to next "{...}" section | "]"

{ | move to previous blank-line separated section | "{"

} | move to next blank-line separated section | "}"

0 | move to column zero

\| | move to column zero

- | move to first non-whitespace of previous line

+ | move to first non-whitespace of next line

W | same as lowercase version. 

E | same as lowercase version. 

B | same as lowercase version.

**Comment by Alexey-T** [comment]
Please one issue per one wish. G is made as full, you can test
