### ISSUE TITLE
Visual mode

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#12]
v = start selecting text for copy/paste/delete etc
V = same but selecting by line

**Comment by Alexey-T** [comment]
How user can stop selecting- after esc? and editor shows selected text?

**Comment by mangobait** [comment]
Yes, editor shows selected text. Escape ALWAYS terminates all commands 
(escape very central to Vim and I remapped my CAPS LOCK to be Escape, as 
many people do).

Once text is selected, people can use:

y (yank) for copy or standard copy command

d (delete) for cut or standard cut command

then p or P for paste (or standard paste command).

Or ESC to kill process.

Some editors buffer this differently depending on if you want to use the 
buffered characters to paste outside of editor, e.g. to a browser etc. 
There might be a logic here, so you have different content, i.e. two 
separate buffers. Or it might be that the planned it badly. Maybe it's 
better to have two buffers, one editor-internal (with y or d) and one 
editor-external (command/control c/x).

**Comment by Alexey-T** [comment]
Visual mode done, keys v V. After you can use normal clipboard commands. Pls test

**Comment by mangobait** [comment]
As noted in #8, V works but v does not. Cursor changes but doesn't seem to
select text.

2017-10-01 6:34 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
v works - it changes caret and NEXT caret move makes selectn. Vim does the same. ??

**Comment by mangobait** [comment]
The v mode still wonky. It will select but v is selecting like V. It
doesn't show that but when you paste it's like that. Will note on Github
but later. And V should really be selecting for word-wrapped line not the
entire line, if there's a difference. Otherwise it has a lot less utility.

E.g. if I select "The v mode", when it pastes, it pastes the entire above
paragraph.

2017-10-05 1:53 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
I dont get idea of ur post. v is like V? here V makes whole lines selection if i move caret down. v makes not whole line selection. it sees x of caret.
"paste is like that"-- ??

**Comment by mangobait** [comment]
v just doesn't start highlighting anything. It changes the cursor and if I
try to select anything, do any kind of copy/paste/cut (with vimkeys) it has
put the whole line/paragraph into the buffer.






2017-10-05 14:30 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
fix made: hjkl now work in Visual mode. pls test.
