### ISSUE TITLE
Movement on screen

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#18]
These should work when in word-wrap mode (or when it's off)

H	home cursor - goto first line on screen
L	goto last line on screen
M	goto middle line on screen

**Comment by Alexey-T** [comment]
Done, please test/close

**Comment by mangobait** [comment]
Nothing. I tried in word-wrap and without word-wrap and no response. Weird.

2017-10-05 3:44 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
you downloaded plugin again via "addon manager / install from Github"? And restarted Cuda?

**Comment by mangobait** [comment]
Okay, got it working now. I did it from "Options>Install from Github" and
from the "Options>Addons Manager>Re-install" and it and it did nothing.
Also, my question, do I need to download each time from the URL, that is
the case?

Now, it is working well for M

H goes to the front of the line that was at the top of the screen. All
writers (aside from songwriters/poets maybe) will always be in word-wrap so
if there is a bit of a paragraph at the top of the screen H will now bring
them to the beginning of the paragraph that was exposed on the screen.

Meaning if "the beginning of the paragraph that was exposed on the screen."
was all you could see at the top of the screen, it will bring you to "H
goes to the front" that wasn't showing before on the screen.

L was behaving funny and I think I realized what's happening (also with H).
They are staying in the same _column_ as they started in. So if you start
in column 50, and there is no column 50 at the target, it produces weird
results like sending the cursor way to the right of the screen.

2017-10-05 14:31 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
"Re-install" list has old version, I update it rarely. new versiion is "Install from github" + enter URL.

**Comment by Alexey-T** [comment]
I will try to fix H L M for paragraphs..

**Comment by mangobait** [comment]
It would be good to centralize it. I.e. not have two or more options and
some that are old.

Can't you do it ALL through the Addons Manager? That would be best.
Definitely bad to have dead ends and options that give you different
results. That confuses people and scares them away. Meaning, I would kill
all other options and force people into using the Addons Manager, for
example. Having to install from a URL means that they have to have the URL
in the first place. A lot of people find the idea of hunting through Github
or Reddit or wherever a huge waste of time. So once we've attracted them to
try out Cuda, it should be all centralized through the manager. And not
have two different routes to the URL thing, with different results.

2017-10-05 15:14 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
OK; will update it now via "Addon manager/ update" (old way via "install from GH" will work too)

**Comment by Alexey-T** [comment]
H L M fixed in Cudatext (Cudatext makes jump)- wait for Cudatext update.
