### ISSUE TITLE
Vim mode toggle (hotkeys) and sticky

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#19]
Ideally vim mode should come default with Cuda (like it does with ST, Atom etc.--more important than minimap for example) but at the very least we need it to be sticky so we don't have to reactivate it every time we restart Cuda. And have hotkeys to do so. A Vimkeybinding user tends to want it to _always_ be in Vim mode. 

The only real choice is that you can have it _start_ in Command Mode or start in Insert Mode. Most editors have it default to start in Insert Mode (so you don't notice till you hit escape) but this could be an option.

**Comment by Alexey-T** [comment]
Done;
update via "install from github". it asks now "Make Vim mode persistent? command/ insert/ cancel"
