### ISSUE TITLE
Replace mode

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#2]
r = replaces current character by next letter typed; then return to normal command mode

R = stays like this until you hit escape (sometimes called Replace mode) so you type over whatever else is on the line, like old computers when you weren't in insert mode

**Comment by Alexey-T** [comment]
'r' will work from next CudaText update [w.o update - works incorrect in replace mode, uppercase chars added]

**Comment by Alexey-T** [comment]
'r' done; wait for Cudatext for Mac updated.

**Comment by Alexey-T** [comment]
'R' done too.

**Comment by Alexey-T** [comment]
I close if it's ok

**Comment by mangobait** [comment]
Works.
