### ISSUE TITLE
remap Esc key ?

### ISSUE THREAD

**Issue by vakosel** [CudaText-addons/cuda_vim_mode#20]
I would like to remap the Esc key with a comination of keys like jj or jk.
Is there a way to do that?

**Comment by Alexey-T** [comment]
Do Vim-mode editors do it? How they allow it?

**Comment by vakosel** [comment]
There is the command map. 
imap jk <Esc>.
The i in front of map means (i)nsert mode. 
Meaning when in insert mode jk is the same as Esc. Esc retains it's functionality. JK is simply an alias to it
--
Sent from Outlook Email App for Android Sunday, 06 January 2019, 11:50PM +02:00 from Alexey  notifications@github.com :

**Comment by Alexey-T** [comment]
Users always remap Esc to j+ something ?

**Comment by vakosel** [comment]
Most of them because is handy.  But definitely not all. Esc needs jump. Jk is just there.. 😊
--
Sent from Outlook Email App for Android Monday, 07 January 2019, 07:10AM +02:00 from Alexey  notifications@github.com :

**Comment by Alexey-T** [comment]
Maybe I can add an option which sets j+something , not sure can add any keys

**Comment by vakosel** [comment]
That would be excellent 
--
Sent from Outlook Email App for Android Monday, 07 January 2019, 10:04AM +02:00 from Alexey  notifications@github.com :

**Comment by vakosel** [comment]
I think is easy.. You can just give only two alternatives because all use either jj or jk. Don't get tired with this. Or either one of them just as an alternatives. All editors that have vim mode, vs code, atom, sublime, idea give this as an alternative.  
For example.. 
https://scotch.io/tutorials/how-to-remap-escape-in-sublime-text-3s-vintage-mode. 
--
Sent from Outlook Email App for Android Monday, 07 January 2019, 10:04AM +02:00 from Alexey  notifications@github.com :

**Comment by Alexey-T** [comment]
I don’t understand - if I type jj in insertion mode - it should do Esc action? But first j char is in the editor. I must undo this chat?

**Comment by vakosel** [comment]
Exactly when you press fast jj or jk (2 chars ) in insert mode it has the action of Esc.
Actually when you press j it writes the j. But if you do it fast you don't see anything. Returns to Esc mode.
--
Sent from Outlook Email App for Android Monday, 07 January 2019, 06:59PM +02:00 from Alexey  notifications@github.com :

**Comment by Alexey-T** [comment]
Please test beta. Use menu item
Plugins/ AddonManager/ Install from github
enter URL: 
https://github.com/cudatext-addons/cuda_vim_mode

2018.01.07
+ add: can remap Esc in insertion mode to "jj" or "jk". Use menu item "Options / Settings-plugins / Vim Mode".

**Comment by vakosel** [comment]
Bingo my friend ! Exactly what i was telling you!

**Comment by Alexey-T** [comment]
made fix for Replace mode. made fix for 'jj'. released in addonManager.
