### ISSUE TITLE
Bug of visual mode

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_vim_mode#21]
@vakosel wrote
I tested your visual mode and it is not working fineWhen you press  v ( for visual single characters) and then press the navigation keys ie h,l to select characterseither left or right, selects the first character and remains stuck. Check it out

**Comment by Alexey-T** [comment]
@vakosel Pls try fix using "AddonManager/ Install from github". seems ok now.

**Comment by vakosel** [comment]
Works ok . But no option for remap only toogle

**Comment by vakosel** [comment]
yeap is ok
