### ISSUE TITLE
Caret on startup in command mode is like edit mode

### ISSUE THREAD

**Issue by acicovic** [CudaText-addons/cuda_vim_mode#23]
Hello there,

This is just a visual thing.

I have set the plugin to start with CudaText in command mode. It does, but the caret doesn't reflect it (it is the classic edit caret). When you enter insert mode and then exit, then it works correctly.

Thanks!

**Comment by Alexey-T** [comment]
i repeated the issue. to fix...

**Comment by Alexey-T** [comment]
made some work. it will be okay/fixed in next Cud, 1.118.x.

**Comment by acicovic** [comment]
Thank you, this will be great.
