### ISSUE TITLE
Add alias keybindings

### ISSUE THREAD

**Issue by acicovic** [CudaText-addons/cuda_vim_mode#24]
Hello there,

Please consider adding the following keybindings:

`yy`: Same as Y
`zz`: Same as z.

Thanks!

**Comment by Alexey-T** [comment]
in http://allhotkeys.com/vim-hotkeys.html
i found that 


["x]yy | Yank [count] lines [into register x]
-- | --
["x]Y | yank [count] lines [into register x] (synonym for yy).

but not found about `zz`.

**Comment by acicovic** [comment]
Hello there,

From https://vimhelp.org/index.txt.html#z

zz                 redraw, cursor line at center of window
z.                  redraw, cursor line to center of window

You can also find other references to this such as:

https://github.com/VSCodeVim/Vim/issues/1475
https://github.com/atom/vim-mode/issues/103

Thanks!

**Comment by acicovic** [comment]
Note that those are lowercase z

**Comment by Alexey-T** [comment]
it is easy to add. will fix it  soon.

**Comment by Alexey-T** [comment]
in the https://vimhelp.org/index.txt.html#z
i see that `zz` is not the same as `z.`

```
z.            z.                 redraw, cursor line to center of window,
                                   cursor on first non-blank
```

**Comment by acicovic** [comment]
OK, so I took a minute to test this.

The difference between `zz` and `z.` is that `z.` is a `zz` that also places the cursor on the first non-blank character (`zz` only adjusts the viewport). In the current cuda_vim_mode implementation, `z.` acts as `zz` (doesn't focus first non-blank character).

**Comment by Alexey-T** [comment]
ok, so i need to change `z.` and add the `zz`.

**Comment by acicovic** [comment]
So theoretically, `z.` should be replaced with `zz`, and you could also add `z.` which would be a `zz` + going to the first non-blank character in the line...

**Comment by Alexey-T** [comment]
workd on this. patch in the Github. pls install from this GH and test. `zz` and `z.`

**Comment by acicovic** [comment]
Is there a guide on how I can install this from Github to CudaText?

Thanks.

**Comment by Alexey-T** [comment]
yes,
https://wiki.freepascal.org/CudaText#How_to_install_plugins_from_GitHub

**Comment by acicovic** [comment]
Tried this and got an [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Alex\\AppData\\Local\\Temp\\cudatext_git_branches.json' error.

But now the problem is that in the process I lost my opened unsaved files that I keep as notes. Can you give me any pointers to see if I can restore them?

Thanks.

**Comment by Alexey-T** [comment]
hmm. i don't understand why you see this error, maybe you run 2 Cud processses? it is  usual procedure to get plugin from github. you can also download the GH repo as Zip. and put it to folder "py"

**Comment by Alexey-T** [comment]
>But now the problem is that in the process I lost my opened unsaved files that I keep as notes. Can you give me any pointers to see if I can restore them?

is this a bug report? how can I see this error?

**Comment by Alexey-T** [comment]
>But now the problem is that in the process I lost my opened unsaved files that I keep as notes. Can you give me any pointers to see if I can restore them?

fixed in Cud 1.118.2, download the update from releases.

**Comment by Alexey-T** [comment]
```
Please consider adding the following keybindings:

yy: Same as Y
```
i cannot do it, cause `y` and `Y` do different things, so `yy` is 2 times of `y` command. see readme of plugin. `y` was made from some Vim online webpage.

**Comment by acicovic** [comment]
@Alexey-T I want to try to recover the lost tabs before I proceed further with testing, see thread above.

Thanks.

**Comment by acicovic** [comment]
> 
> 
> ```
> Please consider adding the following keybindings:
> 
> yy: Same as Y
> ```
> 
> i cannot do it, cause `y` and `Y` do different things, so `yy` is 2 times of `y` command. see readme of plugin. `y` was made from some Vim online webpage.

OK

**Comment by acicovic** [comment]
`zz` and `z.` work correctly for me.

**Comment by Alexey-T** [comment]
thanks for testing. plugin was updated today.
