### ISSUE TITLE
0 key issue

### ISSUE THREAD

**Issue by acicovic** [CudaText-addons/cuda_vim_mode#26]
Hello there,

Pressing 0 (zero key) does not work as expected (it should bring caret to the beginning of the line).

Thanks!

**Comment by Alexey-T** [comment]
okay, i will work on it, soon.

**Comment by Alexey-T** [comment]
I tested command mode (green statusbar). 0 key puts caret to begin of line.
![Screenshot from 2020-12-23 11-46-06](https://user-images.githubusercontent.com/4154978/102977785-8b14f100-4514-11eb-85a6-a00fc4da30ec.png)

how to repeat the issue?

**Comment by Alexey-T** [comment]
readme tells
```
  | - go to column number (if number entered before, else column 1)
  0 - go to line begin (column 1)
  ^ - go to first non-whitespace
  - - go to first non-whitespace, in previous line
  + - go to first non-whitespace, in next line
  $ - go to line end
```

**Comment by acicovic** [comment]
Strange, works for me now. Closing this.
