### ISSUE TITLE
Ctrl+[, Ctrl+H, Ctrl+I, Ctrl+M

### ISSUE THREAD

**Issue by cser** [CudaText-addons/cuda_vim_mode#27]
Is there any way to setup <kbd>Ctrl</kbd>+<kbd>[</kbd> for "Escape behaviuor"?
I know that setup 'jj' or 'jk' is possible, but <kbd>Ctrl</kbd>+<kbd>[</kbd> is standard vim shortcut and its more usable

**Comment by Alexey-T** [comment]
this page
https://www.reddit.com/r/vim/comments/94ao9t/mrw_i_discovered_you_can_use_ctrl_instead_of_esc/
shows

- Ctrl + H is backspace
- Ctrl + I is tab
- Ctrl + J is newline
- Ctrl + M is carriage return

**Comment by Alexey-T** [comment]
I can add them. could you make a long review post of Cud? or some youtube review (long)?

**Comment by cser** [comment]
Wow.
I had no doubt that this is a standard thing.
Any vim editor, be it on Ubuntu, a Mac-OC virtual machine, installed with
Msys GIT-on Windows or installed separately - they all supported Ctrl+[
without any additional settings
I learn it from here: http://miripiruni.org/vimi/

It's not problem for me - don't use vi-mode for my current targets
(moreover, vi-mode has many other problems and bugs, и с русской раскладкой
дело еще хуже чем в самом виме)

However, if you want to extend vi-mode - this thing is needed

вт, 29 дек. 2020 г. в 19:50, Alexey T. <notifications@github.com>:

**Comment by cser** [comment]
> I can add them. could you make a long review post of Cud? or some youtube review (long)?

I think I can, but I haven't figured out where yet. 
https://alternativeto.net/software/cudatext/ - here - ok
https://www.codeproject.com/ - it's about self-made and code, not about using
where else?

**Comment by Alexey-T** [comment]
Hm, alternativeto.net is a collection of some random comments (many are poor), I wanted some good blog post. Habr.com (Ru or En) or some EN site.

Ctrl+[ - will add anyway, but can you write a post?

**Comment by cser** [comment]
I missing on habr. I want to write something, Maybe I'll find a simpler platform.

**Comment by Alexey-T** [comment]
thanks, pls inform here later.

**Comment by Alexey-T** [comment]
is it that Ctrl+[ must invoke this command from command palette?
![Screenshot from 2020-12-29 22-54-32](https://user-images.githubusercontent.com/4154978/103310535-e2d9bd80-4a28-11eb-8dd8-1acb9056242f.png)

**Comment by cser** [comment]
Yes in ideal. The point of this shortcut - prevent moving to far escape
button. Not so far as arrows, but not so close as ctrl+[.

вт, 29 дек. 2020 г., 22:55 Alexey T. <notifications@github.com>:

**Comment by Alexey-T** [comment]
added patch in Github. try to install plugin from GH:
Plugins/ Addon Manager/ Install from Github,
URL: https://github.com/CudaText-addons/cuda_vim_mode

**Comment by cser** [comment]
Tested. For some reason it don't work. Shows "[Vim] Esc key" in status panel and do nothing in insertion mode. Other behavour of Escape doesn't work to. New code exists in py/cuda_vim_mode.

**Comment by Alexey-T** [comment]
what it must do: if you have multi-carets, "cancel" command (Esc key-- cancel command) just removes all carets but first one. did you test with multi-carets?

**Comment by cser** [comment]
Aha, selection clearing and multicarets removing works.
I exit from insert mode expected elso

ср, 30 дек. 2020 г. в 10:49, Alexey T. <notifications@github.com>:

**Comment by Alexey-T** [comment]
do you want that Esc also return from "insert mode" to what?

**Comment by Alexey-T** [comment]
i got it. made the patch, now it must return from insert-mode to command-mode.

**Comment by cser** [comment]
Yes! It works now

ср, 30 дек. 2020 г. в 11:02, Alexey T. <notifications@github.com>:

**Comment by Alexey-T** [comment]
ok, and I welcome the blog post.

**Comment by cser** [comment]
Написал на хабре, оказалось не так сложно получить право на публикацию.
https://habr.com/ru/post/536478/

**Comment by Alexey-T** [comment]
спасибо! начинаю читать.

1) нашел неполное название

> подстановки при поиске с заменой в Cuda.

>формулы в Cuda будет происходить

2) 
>CudaText — это единственный редактор без поддержки замены с подстановками вместо групп совпадения типа \0, \1, ..., поэтому будем пользоваться мультивыделением.

https://wiki.freepascal.org/CudaText#Regular_expressions
тут написано что группы надо писать `$0  ... $9`.

@kvichans @iramsoft @olehl

**Comment by Alexey-T** [comment]
@cser 

>Лечится подсветкой сгенерированного отдельным цветом, опять же в текстовом редакторе.

очень хорошо заюзать тут плагин Куды- Color_Text. может напишите в пост про это? не настаиваю.

**Comment by Alexey-T** [comment]
let's close this, next questions-- to new topics.
