### ISSUE TITLE
Repeat & Undo

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#3]
Vi’s repeat command is very powerful, as it can repeat complex, combined commands.

u – Undo.
. – The . repeats the last full command.  The insert command also functions as a command here. For example, type iunicorn and press Escape. You can then use the . key to insert the word unicorn at the cursor.

**Comment by Alexey-T** [comment]
Done: u
Todo: repeat

**Comment by mangobait** [comment]
u for undo works
. for repeat pending.

2017-10-03 6:42 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
Pls new issue for "." command - it is hard todo
