### ISSUE TITLE
Feature request: Map Ctl-F (page down), Ctl-B (page-up)

### ISSUE THREAD

**Issue by nochiel** [CudaText-addons/cuda_vim_mode#31]
Ref. http://vimdoc.sourceforge.net/htmldoc/scroll.html

**Comment by Alexey-T** [comment]
Seems it's OK wish. and 2nd one.
Maybe you can do something for the project, as 'thanks' for these patches? some blog post (not short), youtube video (not short).

**Comment by nochiel** [comment]
> Seems it's OK wish. and 2nd one.
> Maybe you can do something for the project, as 'thanks' for these patches? some blog post (not short), youtube video (not short).

I'd actually like to contribute a PR with the patches if that's okay? And I'm happy to write a blog post about CudaText as I learn it. (I've just started using it.) I added the following to `init.py` ~but it opens the find/replace dialog at the same time~. 

```py
if key == ord('F'):
                ed_self.cmd(cc.cCommand_KeyPageDown)
                msg('f key')
                return False
```

**Comment by Alexey-T** [comment]
PR's will be okay too, thanks.
