### ISSUE TITLE
status bar is not colored after restart

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_vim_mode#34]
it used to work in the past, but now is broken again.
we should change `on_start` to `on_start2`?

**Comment by Alexey-T** [comment]
Pls try this change, yes, is it working with it?

**Comment by veksha** [comment]
yes. working with it.

also `on_open` and `on_state` can be lazy?

**Comment by veksha** [comment]
working on Windows with on_start2, but what about Linux? is it working even with on_start?

**Comment by Alexey-T** [comment]
If plugin reacts to on_start2, lazy don't have the effect for it

**Comment by Alexey-T** [comment]
> working on Windows with on_start2, but what about Linux? is it working even with on_start?

for me, Vim plugin works as is (w/o change) on linux. isn't it??

**Comment by Alexey-T** [comment]
I mean the statusbar is colored if I set vim mode active after restart (to Command mode).

**Comment by veksha** [comment]
with on_start2 works on Windows, but sometimes this happens:
![image](https://github.com/CudaText-addons/cuda_vim_mode/assets/275333/a63ff3f9-9fa7-4217-954b-3f5c2fc613e5)

strange. i remember how we fixed this already.

**Comment by Alexey-T** [comment]
so this is 'race':
if GitStatus starts later than VimMode's timer (250ms) fires, new cells is black. if before - it's green.

**Comment by veksha** [comment]
`statusbar_proc(h_bar, STATUSBAR_FIND_CELL, value=20) # 20 = last cell (CELL_TAG_INFO)`
this returns None. statusbar has no cells. but i remember that it was working on Windows.
Did you change something related to statusbar recently, @Alexey-T ?

**Comment by Alexey-T** [comment]
no, I did not.

BTW, I tried to fix bad black-BG of GitStatus cell. made fix for GitStatus. in git. pls try it.

**Comment by veksha** [comment]
i think your fix works. so let's just change to on_start2 and close this issue?

**Comment by Alexey-T** [comment]
changed, ok.

**Comment by veksha** [comment]
thanks.
