### ISSUE TITLE
Insert/append at front/back of line

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#4]
I = enter Insertion mode at front of line
A = enter Insertion mode (aka append) at end of line
0 (zero) = moves cursor to front of line
$ = moves cursor to end of line

**Comment by Alexey-T** [comment]
I, A: done, please test.

**Comment by Alexey-T** [comment]
0: done.
4: Readme tells it is number for goto

**Comment by mangobait** [comment]
Sorry, it is the dollar sign (above the 4 on my keyboard).

**Comment by Alexey-T** [comment]
$: done too. Please test, close if ok

**Comment by mangobait** [comment]
Good.

2017-10-03 3:54 GMT-04:00 Alex <notifications@github.com>:
