### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#5]
/ – Type a / followed by some text you want to find and press Enter to quickly move your cursor to the location of the text in the file. For example, if you have the word iguana in your file, type /iguana and press Enter to quickly move the cursor there.

? – Like /, but searches backwards.

f – Type an f followed by any character to quickly move the cursor to the next occurrence of the character on the current line. For example, if you have the line “Hello world” on a line and your cursor is at the beginning of the line, type fo to move to the o in Hello. Type fo again to move to the o in world.

F – Like f, but searches backwards.

**Comment by Alexey-T** [comment]
Done, pls test:
/
?
n
N

todo: f, F

**Comment by Alexey-T** [comment]
Done: f, F
@mangobait Pls test.

**Comment by mangobait** [comment]
/ works
? works
f, F work
n, N work

2017-10-03 6:39 GMT-04:00 Alex <notifications@github.com>:
