### ISSUE TITLE
Join current line to next line

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#6]
J = joins current line to next line

**Comment by Alexey-T** [comment]
It is the same as 
End, Space, Del 
in Cudatext?

**Comment by Alexey-T** [comment]
Done, pls test

**Comment by mangobait** [comment]
Something weird. It eliminates line breaks between paragraphs but doesn't
_join_ a lower line to the current line. Like if this is a line and I want
to join it with

this line, it won't make a continuous line, just eliminate the break
between them.

2017-10-03 12:40 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
Vim does the same? i test- when J pressed here and next line is empty, Vim deletes empty next line.
```
aaa<J>

bb
```
->
```
aaa
bb
```

**Comment by mangobait** [comment]
Yes, but if you do J once, it should give you what you've got; do it a
second time, it should give you:

aaabb


2017-10-05 2:15 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
```
aa
bb

cc

dd
```

I tested on such text. made a fix. Now Cud makes it same as Vim. pls test again

**Comment by mangobait** [comment]
Now when you do the command a second time it deletes the first character of
the next line but does NOT bring it to the current line.

ALSO the cursor should stay on the original line so you could start with:

aa
bb

cc

dd

And then, after you did the command 5 times, get:

aabbccdd

without having to adjust the cursor position. (And without it _ever_
erasing characters.)


2017-10-05 14:26 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
>hen you do the command a second time it deletes the first character of the next line but does NOT bring it to the current line. 

pls, post several lines here, to test them. I will put caret on 1st and press J

**Comment by mangobait** [comment]
The cursor should definitely stay where it is. My testing doesn't and it
still deletes the first character. For example:

Chemistry sits halfway between physics and biology; it’s the middle child
in the scientific family, as dependable as it is overshadowed. On Monday,
the Nobel Prize in Physiology or Medicine was awarded to three researchers
who helped elucidate the mechanics of circadian rhythms, the gene-based
clocks within our cells; on Tuesday, the physics prize honored the
discovery, finally confirmed in 2016, of gravitational waves. By the time
chemistry rolled around, on Wednesday, the siesta of weekdays, it felt in
some ways like just another item on the list. For many people, the
remaining store of Nobel anticipation had already shifted to the Peace
Prize, which will be announced on Friday.

The fact that it’s chemistry doesn’t help—it’s fiddly and subvisible,
architecture for microscopists. Occasionally, the Nobel committee
recognizes an achievement with obvious appeal; last year, the chemistry
prize went to a trio of scientists who built the first molecular-scale
motors and machinery. More commonly, though, the prize recognizes
developments that, although unquestionably essential, at first glance defy
the English language—“for their work on chirally catalysed hydrogenation
reactions,” in 2001; “for palladium-catalyzed cross couplings in organic
synthesis,” in 2010. This year’s short list, according to Chemistry World,
included fundamental work on C–H functionalization and the discovery of
perovskites. One expects that sort of obscurity from physics, which is so
otherworldly anyway. And whatever the medicine prize recognizes, well, it
must be good for us. But chemistry—what exactly does chemistry do again?

The 2017 Nobel Prize in Chemistry, announced this morning, recognizes the
effort of three scientists to shed light on the matter, literally. In 1990,
Richard Henderson, a molecular biologist at Cambridge University, managed
to use an electron microscope, designed for the study of inert material, to
visualize—in three dimensions and at atomic scale—the structure of a
protein found in photosynthetic cells. The chemistry of life, once obscure,
was now visible in astonishing detail. Joachim Frank, a biochemist at
Columbia University, and Jacques Dubochet, of the University of Lausanne,
in Switzerland, made crucial refinements to the method and widened its
application. In the nineteen-seventies, Frank had begun work on a
mathematical technique that eventually enabled the electron microscope to
image not just single, neatly packed groups of proteins in a sample but an
array of them scattered and oriented every which way.


2017-10-05 14:47 GMT-04:00 Alex <notifications@github.com>:
>
> hen you do the command a second time it deletes the first character of
the next line but does NOT bring it to the current line.
>
> pls, post several lines here, to test them. I will put caret on 1st and
press J

**Comment by Alexey-T** [comment]
Ok; I repeated bug on MacOS 10.8; i couldnt see it on Linux

**Comment by Alexey-T** [comment]
Made fix; please update via "Update" dialog (set checkmark in it if not checked)
