### ISSUE TITLE
Copying & Pasting

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_vim_mode#8]
Vi refers to the act of copying as “yanking.”

v – Press v and move the cursor to select a section of text.
y – Copy (yank) the selected text.
p – Paste at cursor.
x – Cuts the selected text. Cuts the character under the cursor if no text is selected
r – Type r and then type another character to replace the character under the cursor.

**Comment by mangobait** [comment]
capital P will paste text above cursor (vs lowercase p will paste it after). This is especially important when using capital V for highlighting.

**Comment by Alexey-T** [comment]
v, r: was done before.

**Comment by Alexey-T** [comment]
Done: y, v, x. Pls test.

**Comment by Alexey-T** [comment]
Done: p, P.

**Comment by mangobait** [comment]
P, p work

y works

d - nope; this doesn't work; it should work as x is currently working.
Thinking about this now, it makes sense that d cuts and puts the text into
the buffer BUT x should not go to buffer. x should only delete (like delete
key)---think about if you've cut something to buffer and need to cut
something to delete it: it should not overwrite your buffer.

V works but v does not. v changes the cursor but doesn't seem to select
text at all.

**Comment by Alexey-T** [comment]
Ok will fix x/d
http://vim.wikia.com/wiki/Copy,_cut_and_paste

**Comment by Alexey-T** [comment]
x: fixed
d: now cuts if selection made. else it begins "delete" prefix.
Pls test

**Comment by mangobait** [comment]
Yes, x and d both work. (Except v is still messed up. Only V works.
Cursor changes but doesn't select.)


2017-10-05 2:11 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
fix made: now hjkl work in Visual mode. pls test.
ps
I needed report that hjkl dont work in visual mode.

**Comment by mangobait** [comment]
vh works
vl works

vw nope
ve nope
vb nope

vj weird
vk weird

Remember I told you that a lot of vimkeys in programmes like Atom and VSC
behave strangely with wrapped text? (The only good one was ST.) So you
didn't have that problem and hjkl could navigate wrapped text (i.e. Cuda
was good, like ST). Now in visual mode you're having that same problem that
j and k (in visual mode) don't know how to handle wrapped text and are
jumping to the next line as though they're all short (almost never the case
for writers).


2017-10-05 14:41 GMT-04:00 Alex <notifications@github.com>:

**Comment by Alexey-T** [comment]
Made fix for j k in visual mode. update via "adddon manager/ update".

**Comment by Alexey-T** [comment]
Made b w e: work in visual mode too. Updated, pls test
